variable "env" {}
variable "tags" {}
variable "component" {}
variable "instance_type" {}
variable "desired_capacity" {}
variable "min_size" {}
variable "max_size" {}
variable "subnets" {}
variable "vpc_id" {}
variable "bastion_cidr" {}
variable "allow_app_to" {}
variable "port" {}